function [delta] = differentiel(xg,yg,x,y,psi)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
delta = sqrt( ...
    (xg-(x-0.5*L+d)*cos(psi))^2 ...
    +(yg-(y-0.5*L+d)*sin(psi))^2 ...
    );
end